### ISSUE TITLE
App show up even if it's not installed

### ISSUE THREAD

**Issue by vanishakesswani** [HaikuArchives/HaikuThemeManager#2]
I have few apps under "Options" which aren't installed yet option for save,apply,preferences is available .
It's broken though.

**Comment by mmuman** [comment]
It doesn't attempt to detect if an app is installed or not, it always shows all the possible parts to apply/save. It should just silently fail if it doesn't find settings for an application anyway.
Some options don't really equate to a single application at all anyway.

A rationale for keeping it that way is if one installs an application later it would already have the theme applied for it. Although this could prevent proper installation if the application detects a setting file is already there while only containing theme info... This would need some thinking indeed.

**Comment by vanishakesswani** [comment]
Probably a friendly popup saying "App not installed" would be good for now?

**Comment by mmuman** [comment]
Or just disable the item (grayed out).

**Comment by vanishakesswani** [comment]
Grayed out features would be the best fix.

**Comment by mmuman** [comment]
Should be fixed now :-)
